# -*- coding: utf-8 -*-
"""Assignment 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fZQ17unZYZQS9gtFA4pmcJ1qsHb6tBJ
"""



"""# Assignment 9

Name: Aziz Sayyad
Roll: 381069
PRN: 22420090
Batch: A3

#### Use appropriate algorithm and perform sentiment analysis for Indian Language.
"""

!pip install transformers torch sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn.functional as F

model_name = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Multilingual Indian language sentences

sentences = [
    # Hindi
    "यह फिल्म बहुत अच्छी है।",

    # Marathi
    "ही सेवा खूप छान आहे.",
    "मला हा अनुभव अजिबात आवडला नाही.",

    # Tamil
    "இந்த படம் மிகவும் அருமையானது.",
    "இந்த சேவை மிகவும் மோசமாக உள்ளது."
]

labels = ['Negative', 'Neutral', 'Positive']

for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt", truncation=True, padding=True)

    outputs = model(**inputs)
    probs = F.softmax(outputs.logits, dim=1)

    predicted_class = torch.argmax(probs).item()

    print("Sentence:", sentence)
    print("Predicted Sentiment:", labels[predicted_class])
    print("Confidence:", round(probs[0][predicted_class].item(), 4))
    print("-" * 50)